on:
  push:
    branches: [ main ]

jobs:
  build-natives:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, name: linux-x64 }
          - { os: macos-14, name: macos-arm64 }
          - { os: macos-13, name: macos-x64 }
          - { os: windows-latest, name: windows-x64 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 21 (for JNI)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.x'
      - name: Build Project
        run: ./gradlew --info :native:publishNativePublicationToMavenLocal
      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: luau-natives-${{ matrix.name }}-1.0.0.jar
          path: native/build/libs/native-${{ matrix.name }}-1.0.0.jar
